version: '3.1'

services:

  data-api:
    image: node:20-alpine
    ports:
      - 11000:3000
    volumes:
      - ./data-api/:/app
      - data-api-cache:/app/.cache
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c 'yarn install && yarn start'

  data-transfer:
    image: node:20-alpine
    volumes:
      - ./data-transfer/:/app
      - data-transfer-cache:/app/.cache
    working_dir: /app
    environment:
      NODE_ENV: development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c 'yarn install && yarn start'

  frontend:
    image: node:20-alpine
    ports:
      - 11010:3000
    volumes:
      - ./frontend/:/app
      - frontend-cache:/app/.cache
    working_dir: /app
    environment:
      NODE_ENV: development
    command: sh -c 'yarn install && yarn start'

  mongo:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: toor
    volumes:
      - ./mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 11081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: toor
      ME_CONFIG_MONGODB_URL: mongodb://root:toor@mongo:27017/

volumes:
  data-api-cache:
  data-transfer-cache:
  frontend-cache: