version: '3.1'

services:

  data-api:
    image: node:20-alpine
    ports:
      - 11000:3000
    volumes:
      - ./data-api/:/app
      - cache:/app/.cache
    working_dir: /app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c 'yarn install && yarn start'

volumes:
  cache: