org: victorkaralkin
service: mancomm-data-transfer
provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  stage: prod
functions:
  job:
    handler: dist/main.handler
    memorySize: 1024
    timeout: 300 # this function isn't bound to API Gateway, so we could allow larger timeouts
    events:
      - schedule:
          name: run-transfer-job
          description: Run a periodic documents transfer from DocumentDB into S3
          rate: rate(15 minutes)
    environment:
      # Lambda prevents using some reserver variable names, so use APP_* prefix for them
      APP_AWS_ACCESS_KEY_ID: ${env:AWS_ACCESS_KEY_ID}
      APP_AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
      APP_AWS_REGION: ${env:AWS_REGION}
      AWS_S3_BUCKET: ${env:AWS_S3_BUCKET}
      DB_COLLECTION_NAME: ${env:DB_COLLECTION_NAME}
      # Alternatively, the db host name / connection string might be taken as a CloudFormation resource output -
      # if the db is declared as a custom CloudFormation resource, which is possible with the Serverless framework.
      DB_CONNECTION_STRING: ${env:DB_CONNECTION_STRING}
    vpc:
      securityGroupIds:
        - sg-a8c330cd
      subnetIds:
        - subnet-2aa0ac5e
        - subnet-8e6e82eb
