org: victorkaralkin
service: mancomm-data-api
provider:
  name: aws
  region: us-west-2
  runtime: nodejs20.x
  stage: prod
functions:
  api:
    handler: dist/main.handler
    memorySize: 2048
    ephemeralStorageSize: 1024 # this is used to cache downloaded html documents
    timeout: 30
    events:
      - http: ANY /
      - http: ANY /{proxy+}
    environment:
      DB_CONNECTION_STRING: ${env:DB_CONNECTION_STRING}
    vpc:
      securityGroupIds:
        - sg-a8c330cd
      subnetIds:
        - subnet-2aa0ac5e
        - subnet-8e6e82eb
